version: '3.8'
services:
  ocserv:
    build: .
    image: ghcr.io/dmitriysafronov/docker-ocs
    restart: unless-stopped
    container_name: ocs
    hostname: www.example.com
    ports:
      - 443:443/udp
      - 443:443
#    volumes:
#      - "/opt/ocserv:/etc/ocserv"
    sysctls:
    - net.ipv4.ip_forward=1
    cap_add:
    - NET_ADMIN
    security_opt:
    - no-new-privileges
